apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    name: flask-app
    app: refactor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-app
      app: refactor-app
  template:
    metadata:
      name: flask-app
      labels:
        name: flask-app
        app: refactor-app
    spec:
      containers:
      - name: flask
        image: criscarba/flask_webserver_image:latest
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_DB_HOST
            value: "mysqldb"
          - name: MYSQL_DB_USER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "mysecretpassword"
          - name: MYSQL_DATABASE
            value: "mysql_db_modulo4"