apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    name: flask-service
    app: refactor-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30004
  selector:
    name: flask-app
    app: refactor-app