apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    name: mysql-service
    app: refactor-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-pod
    app: refactor-app